### ISSUE TITLE
Issue connecting to Dropbox to upload cloud files - Use Case W-1.6

### ISSUE THREAD

**Issue by mhallwac** [samvera-labs/nurax-pre2023#130] opened 2017-11-03 17:21 UTC
### Descriptive summary
Use Case W-1.6 for Chrome on Mac.
Fails to connect to drop box when I click "Browse cloud files"
### Rationale

This should be addressed because users should be able to connect to dropbox in order to upload their cloud files.

### Expected behavior
Connection to Dropbox to allow for cloud files upload.

### Actual behavior
Fails to connect to dropbox and gives message "We're sorry, but something went wrong"

### Steps to reproduce the behavior

* Navigate to the "Work View" page and click the "Edit" button on the top right 
* On the "Edit Work" screen, select the "Files" tab
* select the “Browse cloud files” button
* Select a Source from the dropdown menu at the top left.  Note that Google Drive and Dropbox is not working at this time. Use BOX only
* Select the "Connect to <source>" button.  You will be prompted to log in to your selected source. 

###Image

![image](https://user-images.githubusercontent.com/28707806/32387142-e246a87c-c099-11e7-9071-2ebd27b4d946.png)

**Comment by mjgiarlo** [comment] 2017-11-03 17:26
Hi, @mhallwac! This is a known problem. Thanks for testing and confirming this bug. cc: @julesies

**Comment by mjgiarlo** [comment] 2017-11-03 17:28
Duplicate of #80. Closing.

**Closed as completed by mjgiarlo** 2017-11-03 17:28 UTC
Labels: duplicate
