### ISSUE TITLE
User with Editor role can't see private collection

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#96] opened 2017-10-04 00:07 UTC
Copied here to confirm when fixed. Originally reported by @VivianChu https://github.com/samvera/hyrax/issues/1742

For Hyrax 2.0.0.beta1, User with Editor role can't see a private collection created by other Users.
For Hyrax 2.0.0.alpha, Editor user can see private collection fine.

**Rationale**

To have same editor function as previous hyrax version.

**Expected behavior**

Editor User can see private collection created by Admin or other Users.

**Actual behavior**

Editor User can't see private collection.

**Steps to reproduce the behavior**

Log in as admin
Create a new collection, select private visibility
Log out
Log in as editor
Go to Dashboard: Collections: All collections
Click on a new collection created by admin user
Should see message "You are not authorized to access this page"

**Comment by mjgiarlo** [comment] 2017-10-04 15:10
https://github.com/samvera/hyrax/issues/1742

**Comment by mjgiarlo** [comment] 2017-10-04 20:01
Fixed by https://github.com/curationexperts/nurax/commit/436dab5b69ede39ebad7d74e7a239074327e2d08

**Comment by rjkati** [comment] 2017-10-25 16:28
@mjgiarlo I just tested this functionality and it is not working as expected.

I created a private collection titled "Private Collection to Test Editor Visibility" and gave a test account editor access
![access screen](https://user-images.githubusercontent.com/32644254/32010380-a2d39220-b97f-11e7-857c-cea3b011682e.PNG)

When I log in with the test account, the collection does not display
![nocollection](https://user-images.githubusercontent.com/32644254/32010452-d92a7e74-b97f-11e7-8b88-28607ea5feed.PNG)

**Comment by julesies** [comment] 2017-10-25 16:39
@mjgiarlo direct url access to the collection also doesn't display edit button.

**Comment by mjgiarlo** [comment] 2017-10-26 20:58
I've re-opened the Hyrax bug. thanks!

**Comment by elrayle** [comment] 2017-10-27 13:16
### Hyrax 1.0 - 2.0.0.rc1

In Hyrax 2.0, you cannot see collections you did not create through Dashboard -> Collections -> Your Collections.  I am fairly certain that has been the case for all releases (alpha - beta - rc) of Hyrax.  In Sufia, you could see collections shared with you on the 'Shared with me' tab.

In your steps to reproduce, you reference the All Collections tab.  That tab is only shown to admin users.  Perhaps your expectation that this used to work in alpha was because the test was done with an editor who was also an admin user.

### Hyrax collections-sprint branch

In collections-sprint branch, we have added an additional Managed Collections tab to Dashboard -> Collections.  On that tab, you see collections for which you were granted :manage, :deposit, or :view access.  Users will be able to view the admin show page for a collection if they have any of these access levels granted.

**Comment by elrayle** [comment] 2017-10-27 13:19
FYI... works have the same issue where there is no way to see works shared with you through Dashboard -> Works

FYI... There were previous discussions about incorporating Managed Collections and Managed Works into Hyrax 2.0 branch, but the consensus at the time was not to include it as it was too much new work and we were very close to a 2.0 release.  This will be fixed in 2.1 when collections-sprint branch is merged into master.

**Comment by mjgiarlo** [comment] 2017-10-27 19:00
Fixed in Hyrax, and will be deployed to Nurax in 2-3 minutes. For more on the fix and related work coming soon, see @elrayle's comments :point_up:.

**Closed as completed** 2017-10-27 19:00 UTC
Labels: Moved to Hyrax Issues, MustFix for Release, collections

**Comment by julesies** [comment] 2017-10-27 20:46
@rjkati can you test this again? TY!

**Comment by rjkati** [comment] 2017-10-31 12:31
@julesies Editing is now working as expected.
