### ISSUE TITLE
Can't add a work to an admin set with an Admin set fixed release date setting that has passed

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#108] opened 2017-10-09 14:50 UTC
### Descriptive summary
reported by @rjkati
When trying to add a work to an Admin set with a fixed release date setting that has passed, the work "disappears". 

Expected behavior:
When date of embargo setting passes on the Admin set, one can still submit a work. 

### Steps to reproduce the behavior

1. Submit a work to either Admin set 16, 17, 18
2. Work disappears, page reloads to blank and work is not deposited

**Comment by mjgiarlo** [comment] 2017-10-09 17:30
@julesies Hard to evaluate this one atm. What does "disappears" mean? What is the behavior here from the depositor's perspective? What does the work look like if logged in as admin?

**Comment by vantuyls** [comment] 2017-10-09 17:31
@julesies i can help you test this.

**Comment by vantuyls** [comment] 2017-10-09 17:37
reporting back - by "disappears" on submitting the work, the page reloads to a blank form and the work is nowhere to be found. Similar to behavior in:
https://github.com/samvera/hyrax/issues/1772

**Comment by mjgiarlo** [comment] 2017-10-09 18:25
OK, so the work doesn't disappear exactly. The problem is that:

1. Validation fails (due to some bug, possibly)
2. Validation fails silently, w/o any useful information passed to the user (a bug in and of itself)
3. The form reloads and loses the information that was in it (perhaps a good 2.x feature request)

?

**Comment by julesies** [comment] 2017-10-10 13:55
Yeah it disappears in the way the same way other tickets with embargoes did - which is exactly what you described. I think a bigger issue is that it makes it impossible to add to that admin set at all. I think for the behavior of failing to deposit, is maybe being addressed by https://github.com/samvera/hyrax/pull/1796 ??

**Comment by mjgiarlo** [comment] 2017-10-10 15:27
I believe @jonathandixon has already worked on item 2 from my list above. Item 1 still needs someone to work on it (remedying the underlying bug). Because it relates to embargo/release, you may want to ping Tim (or tag Jonathan again)?

**Comment by mjgiarlo** [comment] 2017-10-11 19:26
I believe this has been fixed in samvera/hyrax#1801, and Nurax now uses the latest Hyrax. Closing.

**Closed as completed by mjgiarlo** 2017-10-11 19:26 UTC
Labels: bug, Moved to Hyrax Issues, collections
