### ISSUE TITLE
Privacy setting labels do not match in different views of same work

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#89] opened 2017-10-02 14:52 UTC
### Descriptive summary
When viewing an embargoed work, marked embargoed to Institution and then Public, the edit screen says, Restricted to PRIVATE instead of institution.
![screen shot 2017-10-02 at 10 01 50 am](https://user-images.githubusercontent.com/4356335/31083392-936ceb42-a75f-11e7-8a4a-c98b25e1498d.png)

![screen shot 2017-10-02 at 10 51 42 am](https://user-images.githubusercontent.com/4356335/31083451-b33d4cc8-a75f-11e7-8f50-0253fd0615dc.png)

### Expected behavior

Settings should match

### Steps to reproduce the behavior

1. Check out this work https://nurax.curationexperts.com/concern/generic_works/9g54xh65x?locale=en
2. Look at differences in settings between edit view and manage embargoes view

**Comment by mjgiarlo** [comment] 2017-10-02 16:52
@julesies will look into this further to determine whether this is a mislabeling error.

**Comment by julesies** [comment] 2017-10-04 16:13
update: testing this further - it seems to only apply to display of work view for embargo setting: Institution.
If institution is selected in either dropdown (Under embargo), the institution restriction is in place - when you test with another user, you can get to works marked institution. The embargo management page also says the correct setting as "institution". The work view edit page will never show Institution under Embargo. It sometimes shows Public and sometime shows Private.

**Comment by mjgiarlo** [comment] 2017-10-04 16:32
@julesies OK. Would you mind writing this up in Hyrax w/ the labels `bug`, `blocker`, and `ready` and the milestone `2.0.0`? Maybe we can tag @tdonohue on that issue too, since he's done a lot of work on this area in the past.

**Comment by tdonohue** [comment] 2017-10-04 21:35
@mjgiarlo and @julesies : I had some time and dug around a bit this afternoon. I can reproduce this in Hyrax, and it not only affects the `visibility_after_embargo` dropdown, but also seems to affect `visibility_before_embargo` dropdown *and* the corresponding before/after dropdowns for leases as well.

I have a PR in the works I can submit to Hyrax.

**Comment by mjgiarlo** [comment] 2017-10-04 21:39
Thanks, @tdonohue!

**Comment by julesies** [comment] 2017-10-04 21:42
moved to hyrax https://github.com/samvera/hyrax/issues/1762

**Comment by tdonohue** [comment] 2017-10-04 21:49
@mjgiarlo and @julesies : PR now available samvera/hyrax#1763

**Comment by tdonohue** [comment] 2017-10-05 13:28
@mjgiarlo or @julesies : This ticket can now be closed, as the PR was merged and corresponding Hyrax ticket closed.  (I'd close this ticket, but I don't have the rights to do so)

**Closed as completed** 2017-10-05 16:04 UTC
Labels: Moved to Hyrax Issues, MustFix for Release, needs more testing
